### ISSUE TITLE
Issue in the demo 

### ISSUE THREAD

**Issue by aradianoff** [getgrav/grav-skeleton-woo-site#1]
I haven't installed the theme but I the demo has a problem (just wanted to let you know).

If you go to the demo page, click on `STYLE GUIDE` and then on another of the navigation items (except home) and it will not work. I think it is due to `STYLE GUIDE`  being and independent page and the other ones being anchors to home.

**Comment by hexplor** [comment]
thanks, gonna fix that. It was working on my local install.

**Comment by hexplor** [comment]
fixed :)
https://github.com/getgrav/grav-theme-woo/commit/6fc21933d20589c5bc74e0897543945e3cdea328
 You can re-download updated file called navigation.html.twig from theme repository - develop branch or you can wait for release.
