### ISSUE TITLE
Demo version: Essential Folder Missing - Accounts Folder

### ISSUE THREAD

**Issue by WhiteWolfSix** [getgrav/grav-skeleton-woo-site#9]
Hi, there is an error due to missing Accounts folder on demo version.
![MissingFolder](https://user-images.githubusercontent.com/24316177/115848300-ff5c9400-a423-11eb-9c90-8b9cd744fdd2.jpg)

**Comment by rhukster** [comment]
I fixed them all yesterday but made a typo on woo `mdkir accounts` :)

Sorted now thanks.

**Comment by WhiteWolfSix** [comment]
> I fixed them all yesterday but made a typo on woo `mdkir accounts` :)
> 
> Sorted now thanks.

Your welcome!
